language: php
php:
  - 5.6
  - 7.0
  - 7.1

before_install:
    - sudo apt-get update && sudo apt-get --reinstall install -qq language-pack-cs

before_script:
  - composer self-update

script:
    - ./tests/run-tests
